config/routes.rb
Rails.application.routes.draw do
	resources :photos, only: [:index, :new, :create, :destroy]
	
  	# application
  	root 'photos#application'
	get '/about' => 'photos#application'
	get '/contactme' => 'photos#application'
	get '/series/:series', to: 'photos#series'
	get 'photos/destroy/:id', to: 'photos#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    has_attached_file :image

	validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  http_basic_authenticate_with name: "hannah", password: "password", except: [:application,:series]

  ############ PRIVATE ############
  def index
    @photos = Photo.order(:series)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      flash[:success] = "The photo was added!"
      redirect_to '/photos/new'
    else
      render 'new'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:success] = "The photo was destroyed."
    redirect_to '/photos'
  end

  ############ PUBLIC ############
  def application
    @photos = Photo.order(:series)
    @photo_covers = @photos.where(:series_cover => true)
    render stream: true
  end

  def series
    @photos = Photo.where(:series => params[:series])
    @series = params[:series]
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :title, :series, :series_cover)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SimpleUploader</title>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag 'application', media: 'all' %>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body ng-app="app" style="min-width: 960px; margin: 0 auto;">
	<!-- navbar -->
	<ng-controller ng-controller="NavCtrl">
		<div class="container">
			<nav class="nav navbar navbar-fixed-top navbar-default">
				<div class="navbar-center">
					Hannah Person Photography
				</div>
				<!-- routes -->
				<div class="navbar-collapse collapse">
					<ul ng-repeat="n in navlistuser" class="nav navbar-nav nav-btn">
						<li><a href="{{n.value}}">{{n.key}}</a></li>
					</ul>
				</div>
			</nav>
		</div>
	</ng-controller>
	<br><br><br>
	<!-- content -->
	<div class="container">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%=key%>"><%=value%></div>
		<% end %>
		<%= yield %>
	</div>
	<br><br>
	<!-- footer -->
	<footer class="footer navbar-default navbar-fixed-bottom">
		<div class="container" style="margin-left: 10%; font-size:18px;">
			<span></span>
		</div>
		<div class="container navbar-right center-right">
			<a href="https://www.linkedin.com/in/hannah-person-58335614b/"><i class="fa fa-linkedin-square"></i></a>
			<a href="https://www.facebook.com/hannah.person.5"><i class="fa fa-facebook-square icon"></i></a> |
			<a onclick="open_email()" style="color:black;"><i class="fa fa-envelope"></i></a>
		</div>
	</footer>
</body>
</html>

app/views/photos/_photo.html.erb
<div class="media">
  <div class="media-left">
  	<figure class="imghvr-blur">
    	<src <%= link_to image_tag(photo.image.url, class: 'animage')%> </src>
    	<figcaption>
    		<center><h4 class="media-heading"><%= photo.title %></h4></center>
    		<%= link_to '', photo_path(photo), method: :delete, data: {confirm: 'Click OK to delete'} %>
    	</figcaption>
	</figure>
  </div>
</div>

app/views/photos/application.html.erb
<div class="container" ng-controller="HomeCtrl">
	<!-- Series -->
	<div class="row" ng-if="homeModal==='/'">
		<% @photo_covers.each do |photo| %>
		<div class="image-wrapper">
			<a href="series/<%=photo.series%>">
				<p>series <%=photo.series%></p>
				<img src="<%=photo.image.url%>" width="365" height="365">
			</a>
		</div>
		<% end %>
	</div>
	<!-- About -->
	<div class="row" ng-show="homeModal==='/about'">
		<div class="aboutme">
			<div id="pic" class="page-section">
				<img src='<%= image_path('about_me.jpg') %>'><br><br><br>
				<button type="button" class="btn btn-primary scroll-link" data-id="aboutmetxt">
  					<span class="glyphicon glyphicon-arrow-down" style="font-size: 14px;"></span>
				</button>
			</div>
			<div id="aboutmetxt" class="page-section page-section-text">
				<h1><b>About Me</b></h1>
				<p>
					Hannah Marie Person, freelance photographer and digital composition artist was born on December 24th, 1990 in Leesburg, Virginia. Amongst her love for illustration, painting, and writing, she found that a digital camera fit her hand the best when she picked up her first Canon at age nine. She soon found her favorite hobby would develop into a lifestyle. After high school, she began taking her first steps into developing her career as a photographer at Virginia Commonwealth University. Though her love for hustle-bustle of city life in the heart of Richmond was strong, she soon recognized the strong desire for a change of location and had a longing to return to the rural, rustic countryside she had grown up in. In 2013, she made a tough but fulfilling decision to move closer to home and transfer to Shepherd University to complete the challenging quest towards her degree in Photography and Computer Imagery. Over the years, Person has been proactive in working with clients practicing her skills of portraiture and event photography. Presently, she has been dedicating most of her time to developing her portfolio as a recent graduate of Shepherd University. Her current theme for her work contests the division between the realm of memory and experience, in which she illustrates in her layered photograph compositions using Adobe Photoshop. She strives to convey reflections on the closely related subjects of archive and memory. Currently, Person resides in Daytona Beach, Florida. She is working on personal work and has high hopes of landing a career in digital image editing and design.
				</p> <br>
				<button type="button" class="btn btn-primary scroll-link" data-id="pic">
  					<span class="glyphicon glyphicon-arrow-up" style="font-size: 14px"></span>
				</button>
			</div>
		</div>
	</div>
	<!-- Contact -->
	<div class="row" ng-show="homeModal==='/contactme'">
		<h1>contact me</h1>
	</div>

</div>

app/views/photos/index.html.erb
<div class="page-header">
	<h1>Photo Collection: <%= @photos.count %></h1>
	<button class="btn btn-primary" onclick="location.href='/photos/new'">new</button>
</div>

<%=@user%>
<h3>covers</h3>
<% @photos.each do |photo| %>
	<% if photo.series_cover %>
		<div class="image-wrapper">
			<a>
				<p>series <%=photo.series%></p>
				<img id="<%photo.id%>" src="<%=photo.image.url%>" onclick="delete_photo(<%=photo.id%>)" width="365" height="365">
			</a>
		</div>
	<% end %>
<% end %>
<hr>

<h3>all</h3>
<% @photos.each do |photo| %>
	<% if !photo.series_cover %>
		<div class="image-wrapper">
			<a>
				<p>series <%=photo.series%></p>
				<img id="<%photo.id%>" src="<%=photo.image.url%>" onclick="delete_photo(<%=photo.id%>)" width="365" height="365">
			</a>
			<%=photo.title%>
		</div>
	<% end %>
<% end %>
<hr>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<div class="col-sm-6 col-md-offset-3">

<%= form_for @photo do |f| %>
  <%= render 'shared/errors', object: @photo %>

  <div class="form-group">
    <%= f.label 'Cover', class: 'col-2 col-form-label'%>
    <%= f.check_box :series_cover %>
  </div>

  <div class="form-group">
    <%= f.label :series, class: 'col-2 col-form-label' %><br>
    <%= f.select :series, [['one',1],['two',2],['three',3],['four',4],['five',5],['six',6],['seven',7],['eight',8],['nine',9],['ten',10],['eleven',11],['twelve', 12]]%>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/photos/series.html.erb
<!-- picture display | series/:series -->
<div class="container">
	<ng-controller ng-controller="SeriesCtrl">
		<!-- Images -->
		<div class="row">
			<% @photos.each do |photo| %>
			<div class="view hm-zoom image-wrapper-series">
				<img id="<%=photo.id%>" class="mySlides" src="<%=photo.image.url%>" data-toggle="modal" data-target="#myModal" width="365" height="365"/>
			</div>
			<% end %>
			<!-- Modal -->
			<div id="myModal" class="modal fade" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-body">
							<div class="row">
								<button class="w3-button w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
								<button class="w3-button w3-display-right" onclick="plusDivs(+1)">&#10095;</button>
								<img id="modalPhoto" class="img-responsive" src="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</ng-controller>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>